apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: cmVkaGF0
---
apiVersion: v1
kind: Pod
metadata:
  name: mysecret
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secrets
          mountPath: "/secret"
          readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: mysecret
        items:
          - key: username
            path: my-group/my-username
