apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - cat /abc/my-group/my-username
    volumeMounts:
      - name: secrets
        mountPath: "/abc"
        readOnly: true

  volumes:
    - name: secrets
      secret:
        secretName: mysecret
        items:
          - key: username
            path: my-group/my-username
