apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ninjia
  labels:
    run: ninjia
spec:
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
  selector:
    run: ninjia
