apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninjia
spec:
  selector:
    matchLabels:
      run: ninjia
  replicas: 2
  template:
    metadata:
      labels:
        run: ninjia
    spec:
      containers:
        - name: ninjia
          image: 192.168.0.115:5001/app:1
          ports:
            - containerPort: 80
