apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-monorepo-container
spec:
  serviceAccountName: argo
  entrypoint: imagebuild
  arguments:
    parameters:
    - name: PROJECT_NAME
      value: "ninjia-group-workspace"
    - name: BRANCH_NAME
      value: "build-push-image"
    - name: CHANNEL_NAME
      value: "stage"
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

  templates:
  - name: imagebuild
    inputs:
      parameters:
      - name: PROJECT_NAME
        value: "{{workflow.arguments.parameters.PROJECT_NAME}}"
      - name: BRANCH_NAME
        value: "{{workflow.arguments.parameters.BRANCH_NAME}}"
      - name: CHANNEL_NAME
        value: "{{workflow.arguments.parameters.CHANNEL_NAME}}"
    dag:
      tasks:
      - name: checkout
        template: checkout
        arguments:
          parameters:
          - name: PROJECT_NAME
            value: "{{inputs.parameters.PROJECT_NAME}}"
          - name: BRANCH_NAME
            value: "{{inputs.parameters.BRANCH_NAME}}"
      - name: build
        template: build
        arguments:
          parameters:
            -
            - name: PROJECT_NAME
              value: "{{inputs.parameters.PROJECT_NAME}}"
            - name: BRANCH_NAME
              value: "{{inputs.parameters.BRANCH_NAME}}"
        depends: checkout.Succeeded
      - name: update-image
        template: update-image
        arguments:
          parameters:
            - name: PROJECT_NAME
              value: "{{inputs.parameters.PROJECT_NAME}}"
        depends: build.Succeeded
      - name: call-update-channel-wf
        template: call-update-channel-wf
        arguments:
          parameters:
            - name: IMAGE_ID
              value: "{{tasks.update-image.outputs.parameters.IMAGE_ID}}"
            - name: CHANNEL_NAME
              value: "{{inputs.parameters.CHANNEL_NAME}}"
        depends: update-image.Succeeded

  - name: checkout
    timeout: "30m"
    inputs:
      parameters:
      - name: BRANCH_NAME
      - name: PROJECT_NAME
    script:
      image: alpine/git:latest
      command: ["/bin/sh", "-ex"]
      source: |
        mkdir /workspace/{{inputs.parameters.PROJECT_NAME}}
        git clone --depth=1 --single-branch --branch {{inputs.parameters.BRANCH_NAME}} "https://github.com/emilyzeng1977/{{inputs.parameters.PROJECT_NAME}}.git" "/workspace/{{inputs.parameters.PROJECT_NAME}}"
      volumeMounts:
      - name: workdir
        mountPath: /workspace

  - name: build
    timeout: "30m"
    inputs:
      parameters:
        - name: BRANCH_NAME
        - name: PROJECT_NAME
    script:
      image: alpine/git:latest
      command: ["/bin/sh", "-ex"]
      source: |
        ls -alt /workspace/{{inputs.parameters.PROJECT_NAME}}/
      volumeMounts:
        - name: workdir
          mountPath: /workspace

  - name: update-image
    timeout: "30m"
    inputs:
      parameters:
        - name: PROJECT_NAME
    outputs:
      parameters:
        - name: IMAGE_ID
          valueFrom:
            path: "/workspace/image_id"
    container:
      image: gcr.io/kaniko-project/executor:v1.9.0-debug
      args:
        - --context=/workspace/{{inputs.parameters.PROJECT_NAME}}/app
        - --destination=192.168.0.115:5001/app:2
        - --dockerfile=/workspace/{{inputs.parameters.PROJECT_NAME}}/app/Dockerfile
          
      volumeMounts:
        - name: workdir
          mountPath: /workspace

  - name: call-update-channel-wf
    timeout: "30m"
    inputs:
      parameters:
        - name: IMAGE_ID
        - name: CHANNEL_NAME
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: call-update-channel-
        spec:
          workflowTemplateRef:
            name: update-channel
          arguments:
            parameters:
            - name: CHANNEL_NAME
              value: {{inputs.parameters.CHANNEL_NAME}}
            - name: IMAGE_ID
              value: {{inputs.parameters.IMAGE_ID}}
