apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-monorepo-container
spec:
  serviceAccountName: argo
  entrypoint: imagebuild
  arguments:
    parameters:
    - name: PROJECT_NAME
      value: "ninjia-group-workspace"
    - name: BRANCH_NAME
      value: "02-k8s-create-push-image"
    - name: CHANNEL_NAME
      value: "stage"
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

  templates:
  - name: imagebuild
    inputs:
      parameters:
      - name: PROJECT_NAME
        value: "{{workflow.arguments.parameters.PROJECT_NAME}}"
      - name: BRANCH_NAME
        value: "{{workflow.arguments.parameters.BRANCH_NAME}}"
      - name: CHANNEL_NAME
        value: "{{workflow.arguments.parameters.CHANNEL_NAME}}"
    dag:
      tasks:
      - name: checkout
        template: checkout
        arguments:
          parameters:
          - name: PROJECT_NAME
            value: "{{inputs.parameters.PROJECT_NAME}}"
          - name: BRANCH_NAME
            value: "{{inputs.parameters.BRANCH_NAME}}"
      - name: build
        template: build
        arguments:
          parameters:
            - name: BRANCH_NAME
              value: "{{inputs.parameters.BRANCH_NAME}}"
        depends: checkout.Succeeded
      - name: update-image
        template: update-image
        depends: build.Succeeded
      - name: call-update-channel-wf
        template: call-update-channel-wf
        arguments:
          parameters:
            - name: IMAGE_ID
              value: "{{tasks.update-image.outputs.parameters.IMAGE_ID}}"
            - name: CHANNEL_NAME
              value: "{{inputs.parameters.CHANNEL_NAME}}"
        depends: update-image.Succeeded

  - name: checkout
    timeout: "30m"
    inputs:
      parameters:
      - name: PROJECT_NAME
      - name: BRANCH_NAME
    script:
      image: alpine/git:latest
      command: ["/bin/sh", "-ex"]
      source: |
        date;
        PROJECT_NAME="{{inputs.parameters.PROJECT_NAME}}"
        BRANCH_NAME="{{inputs.parameters.BRANCH_NAME}}"
        echo ${BRANCH_NAME}
        git clone --branch ${BRANCH_NAME} "https://github.com/emilyzeng1977/${PROJECT_NAME}.git" "/workspace/${PROJECT_NAME}"
        ls -alt /workspace/${PROJECT_NAME}
      volumeMounts:
      - name: workdir
        mountPath: /workspace

  - name: build
    timeout: "30m"
    inputs:
      parameters:
        - name: BRANCH_NAME
    script:
      image: alpine/git:latest
      command: ["/bin/sh", "-ex"]
      source: |
        echo "build"
        ls /workspace
        ls /workspace/app
#        ls -alt /workspace/{{inputs.parameters.BRANCH_NAME}}/
      volumeMounts:
        - name: workdir
          mountPath: /workspace

  - name: update-image
    timeout: "30m"
    outputs:
      parameters:
        - name: IMAGE_ID
          valueFrom:
            path: "/workspace/image_id"
    container:
      resources:
        requests:
          cpu: "2000m"
      image: gcr.io/kaniko-project/executor:debug
      env:
        - name: AWS_ACCESS_KEY_ID
          value: AKIASTL6GZUTID6S2APB
        - name: AWS_SECRET_ACCESS_KEY
          value: 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
      args:
        - --destination=179042700582.dkr.ecr.ap-southeast-2.amazonaws.com/app:latest
        - --context=/workspace/app/
      volumeMounts:
        - name: workdir
          mountPath: /workspace

  - name: call-update-channel-wf
    timeout: "30m"
    inputs:
      parameters:
        - name: IMAGE_ID
        - name: CHANNEL_NAME
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: call-update-channel-
        spec:
          workflowTemplateRef:
            name: update-channel
          arguments:
            parameters:
            - name: CHANNEL_NAME
              value: {{inputs.parameters.CHANNEL_NAME}}
            - name: IMAGE_ID
              value: {{inputs.parameters.IMAGE_ID}}
