apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - 00-namespace.yaml
  - 00-account.yml
  - 00-role.yml
  - 01-role-binding.yml
  - 02-traefik.yml
  - 02-traefik-services.yml
