apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      $patch: replace
      containers:
        - name: mini-nginx
          image: zengemily79/mini-nginx:1
          ports:
            - containerPort: 8080
